### ISSUE TITLE
Feature request - switchable performance.ini files

### ISSUE THREAD

**Issue by ebrown3k** [probonopd/MiniDexed#125]
I think adding a way to have multiple performance.ini files and swap them through the UI/menu would add a ton of usefulness to this in a live performance setting.

**Comment by probonopd** [comment]
Maybe a structure similar to sysex should be used, along the lines of `performances/001_PerformanceName.ini`, `performances/002_PerformanceName2.ini`

**Comment by craigyjp** [comment]
The original DX7 only had one performance mode unfortunately, but the MK2 and S models had 32 or 64 performance modes. So it would be nice to have the extra performance patches.

**Comment by arsamus** [comment]
> Maybe a structure similar to sysex should be used, along the lines of `performances/001_PerformanceName.ini`, `performances/002_PerformanceName2.ini`

This will be a good enhancement it is necessary for those that use minidexed as a multitumbral synth. Selection of saved performances is the way to change this multitumbral paches, otherwise you have to navigate on the menus and ajust the parameters to set the decired patch. 

Other important enhancement could be load and saving performances and sysex banks on an USB pendrive. this avoid to access to the SD to add new roms or to modify performance files.

**Comment by probonopd** [comment]
Do you think you could do it @arsamus?

**Comment by arsamus** [comment]
> Do you think you could do it @arsamus?

Let me see if I can do something.
