### ISSUE TITLE
case sensitivity issue in performance/ directory

### ISSUE THREAD

**Issue by patrickdowling** [probonopd/MiniDexed#538]
I think there's case sensitivity conflict/duplicate file from commit https://github.com/probonopd/MiniDexed/commit/375900b9ec8d026bb0f8e3668cdf0e9e5964739b (maybe)?
```
performance/000001_mDX-Piano.ini
performance/000001_mDx-Piano.ini
```
Took me a while to spot (D**x** and D**X**) but it confuses git status on OS X at least 😄
Looks like DX is the newer version but Dx would be consistent with other filenames?

**Comment by Banana71** [comment]
Hello Patrick,
it happens that I change and further develop existing performances. I often have several versions of a performance on the SD card before I can decide on just one. Then I copy the modified Performance to its original place. For some reason I also changed the filename. The 000001_mDX-Piano.ini file is up to date.
The file 000001_mDx-Piano.ini and 000055_Choir 1TG_Dry.ini can be deleted.
If the new performances are then copied to the existing folder on the SD card, problems will probably arise. It is best to always rename the old performance folder or otherwise secure it in some way and then copy the new versions.
