### ISSUE TITLE
MiniDexed on "normal" OS

### ISSUE THREAD

**Issue by grbfst** [probonopd/MiniDexed#597]
I'm building a touch oriented instrument with a Raspberry pi for someone who works with the (demented) elderly. I'm using a MCP3008 (or maybe two) to convert touch to midi. Since this is running on python I'm wondering if there is a way to run MiniDexed without the bare metal but with the LCD screen and rotary encoder, so on Raspberry Pi OS lite. 
If so, I can run the touch to midi python program on the same Raspberry,

**Comment by probonopd** [comment]
Hi @grbfst.

Since MiniDexed is based on Circle and there is currently no way to run Circle applications on Linux, this is not possible at this time unfortunately.

You may achieve a similar solution by running the Dexed standalone application on Raspberri Pi OS, or by running the Dexed VSTi inside a VST host.
